stages:
  - test
  - package
  - deploy

test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-17-focal
  script:
   - mvn compile
   - mvn test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

package:
  stage: package
  image: maven:3.9.9-eclipse-temurin-17-focal
  script:
   - mvn package
   - mvn javadoc:javadoc
  artifacts:
    when: always
    paths:
      - target/*.jar
      - target/libs
      - target/reports/apidocs
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

deploy:
  variables:
     DOCKER_TLS_CERTDIR: ''
  image: docker:stable
  stage: deploy
  dependencies:
    - package
  services:
    - docker:dind-rootless
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --force-rm --pull -t "$CI_REGISTRY_IMAGE" -f Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  dependencies:
    - package
  script:
  - mkdir public
  - cp -a target/reports/apidocs/* public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

